
name: Build, test, package


on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  cxx-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@v5.4.2
    with:
      warnings-to-ignore: 'ld. warning. ignoring duplicate libraries. \'-lm\''

  python-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@v5.4.2
    with:
      test-notebooks: false
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
